name: 'deploy-yard-to-pages'
description: 'Deploy YARD documents to GitHub Pages'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'upload'
  color: 'blue'
inputs:
  output-dir:
    description: 'YARD generated HTMls in'
    required: true
    default: 'doc'
  ruby-version:
    description: 'YARD runner will be executed with this ruby version'
    required: true
    default: '3.3'
outputs:
  page_url:
    description: 'github page url'
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: 'composite'
  steps:
    # libyaml is needed for psych, see https://github.com/actions/runner-images/issues/9895
    # GitHub installs libyaml-dev in latest runners, but often dropped in new runners.
    # So, make sure to check here even if using runner installed.
    - name: Install libyaml
      if: runner.os == 'Linux'
      run: sudo apt-get install --no-install-recommends --assume-yes libyaml-dev
    - name: Checkout
      uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec yard
      shell: bash
    - uses: actions/configure-pages@v5
    - uses: actions/upload-pages-artifact@v3
      with:
        # By default, upload the docs directory
        path: ${{ inputs.output-dir }}
    - id: deployment
      uses: actions/deploy-pages@v4
