name: 'deploy-yard-to-pages'
description: 'Deploy YARD documents to GitHub Pages'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'upload'
  color: 'blue'
inputs:
  output-dir:
    description: 'YARD generated HTMls in'
    required: true
    default: 'doc'
  ruby-version:
    description: 'YARD runner will be executed with this ruby version'
    required: true
    default: '3.2'
outputs:
  page_url:
    description: 'github page url'
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec yard
      shell: bash
    - uses: actions/configure-pages@v3
    - uses: actions/upload-pages-artifact@v1
      with:
        # By default, upload the docs directory
        path: ${{ inputs.output-dir }}
    - id: deployment
      uses: actions/deploy-pages@v2
