name: 'deploy-yard-to-pages'
description: 'Deploy YARD documents to GitHub Pages'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'upload'
  color: 'blue'
inputs:
  output-dir:
    description: 'YARD generated HTMls in'
    required: true
    default: 'doc'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec yard
      shell: bash
    - uses: actions/configure-pages@v2
    - uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: ${{ inputs.output-dir }}
    - id: deployment
      uses: actions/deploy-pages@v1
