name: CI - Nix
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-nix.yml'
      - '**.nix'
      - 'flake.*'
      - '.ruby-version'
      - 'dprint.json'
  pull_request:
    paths:
      - '.github/workflows/ci-nix.yml'
      - '**.nix'
      - 'flake.*'
      - '.ruby-version'
      - 'dprint.json'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

jobs:
  tasks:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix flake check
      - run: nix develop --command echo 'This step should be done before any other "nix develop" steps because of measuring Nix build time'
      - name: Log current versions
        run: nix develop --command rake deps
      - run: nix develop --command rake lint
